### ISSUE TITLE
Update for Android-10

### ISSUE THREAD

**Issue by Scissordragonboy** [android-linux-stable/msm-3.18#11]
3.18-r34 seems like for android-9(pie). It can boot android-10. It will be very helpful for us, if you could update your repo with 3.18-r41 android-10(q).

 Thanks you.

If you could have a look into it. It will help us alot.

**Comment by nathanchance** [comment]
Given that 3.18 is dead from kernel.org and I am limited on cycles to do kernel/common merges, I am going to leave 3.18 at Android 9. Thanks.

**Comment by Scissordragonboy** [comment]
At least update pie one with latest common/kernel 3.18 from aosp.
