### ISSUE TITLE
error file /drivers/platform/msm/qpnp-revid.c  KERNEL MSM 3.18

### ISSUE THREAD

**Issue by nathancmiguel** [android-linux-stable/msm-3.18#8]
CC      drivers/platform/msm/qpnp-revid.o
Android GCC has been deprecated in favor of Clang, and will be removed from
Android in 2020-01 as per the deprecation plan in:
https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/GCC_4_9_DEPRECATION.md

../drivers/platform/msm/qpnp-revid.c: In function 'qpnp_read_byte':
../drivers/platform/msm/qpnp-revid.c:80:47: error: 'struct spmi_device' has no member named 'sid'
  rc = spmi_ext_register_readl(spmi->ctrl, spmi->sid, addr, &val, 1);
                                               ^
../drivers/platform/msm/qpnp-revid.c:80:31: warning: passing argument 1 of 'spmi_ext_register_readl' from incompatible pointer type
error, forbidden warning: qpnp-revid.c:80
make[4]: *** [../scripts/Makefile.build:258: drivers/platform/msm/qpnp-revid.o] Error 1
make[3]: *** [../scripts/Makefile.build:402: drivers/platform/msm] Error 2
make[2]: *** [../scripts/Makefile.build:402: drivers/platform] Error 2
make[1]: *** [/home/nathan/Git/AndroidDev/Kernel/msm-3.18/Makefile:968: drivers] Error 2
make[1]: Leaving directory '/home/nathan/Git/AndroidDev/Kernel/msm-3.18/out'
make: *** [Makefile:145: sub-make] Error 2

to be more precise of the error in line 80 of this file, I tried to test other versions of the kernel but it is not working, same error

**Comment by nathanchance** [comment]
I test both `msm-perf_defconfig` and `msm8937-perf_defconfig` and I don't see this error.

Regardless, this is all CAF code so it isn't an android-linux-stable bug. A cursory survey shows that CAF appeared to misname that variable in its definition: https://github.com/android-linux-stable/msm-3.18/blob/kernel.lnx.3.18.r34-rel/include/linux/spmi.h#L54

I don't know what other implications that will have though. Good luck!
